
import React, { createContext, useContext, useState, ReactNode } from "react";

type Language = "en" | "de";

interface Translation {
  [key: string]: string;
}

interface LanguageContextType {
  language: Language;
  t: (key: string) => string;
  setLanguage: (language: Language) => void;
}

const translations: Record<Language, Translation> = {
  en: {
    greeting: "Welcome to GreenGuide",
    home: "Home",
    strains: "Strains",
    clubs: "Cannabis Clubs",
    journal: "Journal",
    community: "Community",
    map: "Map",
    profile: "Profile",
    settings: "Settings",
    login: "Login",
    register: "Register",
    logout: "Logout",
    findClub: "Find a Club Near You",
    searchPlaceholder: "Search for strains, clubs, or topics",
    viewProfile: "View Profile",
    featuredStrains: "Featured Strains",
    exploreStrains: "Explore Cannabis Strains",
    findYourStrain: "Discover the perfect strain for your needs with detailed profiles including effects, medicinal benefits, and flavor profiles.",
    strainExplorer: "Strain Explorer",
    thcLevel: "THC",
    cbdLevel: "CBD",
    viewAll: "View All",
    popular: "Popular",
    nearMe: "Near Me",
    yourJournal: "Your Journal",
    recentEntries: "Recent Entries",
    trackConsumption: "Track Your Consumption",
    addEntry: "Add Entry",
    filter: "Filter",
    filterStrains: "Filter Strains",
    filterBy: "Filter by",
    type: "Type",
    effects: "Effects",
    medicalUses: "Medical Uses",
    applyFilters: "Apply",
    reset: "Reset",
    noStrainsFound: "No strains found",
    details: "Details",
    userReviews: "User Reviews",
    description: "Description",
    flavors: "Flavors",
    cannabinoidProfile: "Cannabinoid Profile",
    trackEffectiveness: "Track Effectiveness",
    journalDescription: "Keep a personal journal to track this strain's effects on you over time.",
    startJournal: "Start Journal",
    askCommunity: "Ask the Community",
    askCommunityDescription: "Have questions about this strain? Get insights from experienced users.",
    askQuestion: "Ask a Question",
    relaxing: "Relaxing",
    energizing: "Energizing",
    creative: "Creative",
    focused: "Focused",
    sleepy: "Sleepy",
    euphoric: "Euphoric",
    uplifted: "Uplifted",
    happy: "Happy",
    hungry: "Hungry",
    dry_mouth: "Dry Mouth",
    dry_eyes: "Dry Eyes",
    paranoia: "Paranoia",
    dizziness: "Dizziness",
    anxiety: "Anxiety",
    headache: "Headache",
    sideEffects: "Side Effects",
    effectiveness: "Effectiveness",
    rating: "Rating",
    yourReview: "Your Review",
    shareYourExperience: "Share your experience with this strain...",
    submitReview: "Submit Review",
    submitting: "Submitting...",
    cancel: "Cancel",
    writeReview: "Write a Review",
    noReviewsYet: "No reviews yet. Be the first to share your experience!",
    saveToFavorites: "Save to Favorites",
    strainNotFound: "Strain Not Found",
    strainNotFoundMessage: "The strain you're looking for could not be found.",
    backToStrains: "Back to Strains",
    previousStrain: "Previous Strain",
    nextStrain: "Next Strain",
    noImage: "No Image",
    similarStrains: "Similar Strains",
    moreDetails: "More Details",
    potency: "Potency",
    dominant: "Dominant",
    moderate: "Moderate",
    mild: "Mild",
    highTHC: "High THC",
    highCBD: "High CBD",
    balanced: "Balanced",
    growInfo: "Growing Information",
    floweringTime: "Flowering Time",
    height: "Height",
    yield: "Yield",
    difficulty: "Difficulty",
    indoorOutdoor: "Indoor/Outdoor",
    genetics: "Genetics",
    lineage: "Lineage",
    parentStrains: "Parent Strains",
    topTerpenes: "Top Terpenes",
    awards: "Awards",
    bestFor: "Best For",
    notRecommendedFor: "Not Recommended For",
    consumptionMethods: "Consumption Methods",
    smoking: "Smoking",
    vaping: "Vaping",
    edibles: "Edibles",
    tinctures: "Tinctures",
    concentrates: "Concentrates",
    topicals: "Topicals",
    tryDifferentSearch: "Try different search terms or filter criteria",
    results: "results found",
    reviews: "Reviews",
    reviewsInSeparateTab: "Reviews can be found in the Reviews tab above",
  },
  de: {
    greeting: "Willkommen bei GreenGuide",
    home: "Startseite",
    strains: "Sorten",
    clubs: "Cannabis-Clubs",
    journal: "Tagebuch",
    community: "Community",
    map: "Karte",
    profile: "Profil",
    settings: "Einstellungen",
    login: "Anmelden",
    register: "Registrieren",
    logout: "Abmelden",
    findClub: "Finde einen Club in deiner Nähe",
    searchPlaceholder: "Suche nach Sorten, Clubs oder Themen",
    viewProfile: "Profil anzeigen",
    featuredStrains: "Ausgewählte Sorten",
    exploreStrains: "Cannabis-Sorten entdecken",
    findYourStrain: "Entdecke die perfekte Sorte für deine Bedürfnisse mit detaillierten Profilen zu Wirkungen, medizinischen Vorteilen und Geschmacksprofilen.",
    strainExplorer: "Sorten-Explorer",
    thcLevel: "THC",
    cbdLevel: "CBD",
    viewAll: "Alle anzeigen",
    popular: "Beliebt",
    nearMe: "In der Nähe",
    yourJournal: "Dein Tagebuch",
    recentEntries: "Neueste Einträge",
    trackConsumption: "Verfolge deinen Konsum",
    addEntry: "Eintrag hinzufügen",
    filter: "Filter",
    filterStrains: "Sorten filtern",
    filterBy: "Filtern nach",
    type: "Typ",
    effects: "Wirkungen",
    medicalUses: "Medizinische Anwendungen",
    applyFilters: "Anwenden",
    reset: "Zurücksetzen",
    noStrainsFound: "Keine Sorten gefunden",
    details: "Details",
    userReviews: "Nutzerbewertungen",
    description: "Beschreibung",
    flavors: "Aromen",
    cannabinoidProfile: "Cannabinoid-Profil",
    trackEffectiveness: "Wirksamkeit verfolgen",
    journalDescription: "Führe ein persönliches Tagebuch, um die Wirkung dieser Sorte auf dich im Laufe der Zeit zu verfolgen.",
    startJournal: "Tagebuch starten",
    askCommunity: "Frage die Community",
    askCommunityDescription: "Hast du Fragen zu dieser Sorte? Erhalte Einblicke von erfahrenen Nutzern.",
    askQuestion: "Frage stellen",
    relaxing: "Entspannend",
    energizing: "Energetisierend",
    creative: "Kreativ",
    focused: "Fokussiert",
    sleepy: "Schläfrig",
    euphoric: "Euphorisch",
    uplifted: "Gehoben",
    happy: "Glücklich",
    hungry: "Hungrig",
    dry_mouth: "Trockener Mund",
    dry_eyes: "Trockene Augen",
    paranoia: "Paranoia",
    dizziness: "Schwindel",
    anxiety: "Angstzustände",
    headache: "Kopfschmerzen",
    sideEffects: "Nebenwirkungen",
    effectiveness: "Wirksamkeit",
    rating: "Bewertung",
    yourReview: "Deine Bewertung",
    shareYourExperience: "Teile deine Erfahrung mit dieser Sorte...",
    submitReview: "Bewertung abgeben",
    submitting: "Wird übermittelt...",
    cancel: "Abbrechen",
    writeReview: "Bewertung schreiben",
    noReviewsYet: "Noch keine Bewertungen. Sei der Erste, der seine Erfahrung teilt!",
    saveToFavorites: "Zu Favoriten hinzufügen",
    strainNotFound: "Sorte nicht gefunden",
    strainNotFoundMessage: "Die gesuchte Sorte konnte nicht gefunden werden.",
    backToStrains: "Zurück zu Sorten",
    previousStrain: "Vorherige Sorte",
    nextStrain: "Nächste Sorte",
    noImage: "Kein Bild",
    similarStrains: "Ähnliche Sorten",
    moreDetails: "Mehr Details",
    potency: "Stärke",
    dominant: "Dominant",
    moderate: "Moderat",
    mild: "Mild",
    highTHC: "Hoher THC-Gehalt",
    highCBD: "Hoher CBD-Gehalt",
    balanced: "Ausgewogen",
    growInfo: "Anbauinformationen",
    floweringTime: "Blütezeit",
    height: "Höhe",
    yield: "Ertrag",
    difficulty: "Schwierigkeit",
    indoorOutdoor: "Indoor/Outdoor",
    genetics: "Genetik",
    lineage: "Abstammung",
    parentStrains: "Elternsorten",
    topTerpenes: "Wichtigste Terpene",
    awards: "Auszeichnungen",
    bestFor: "Gut geeignet für",
    notRecommendedFor: "Nicht empfohlen für",
    consumptionMethods: "Konsummethoden",
    smoking: "Rauchen",
    vaping: "Verdampfen",
    edibles: "Essbare Produkte",
    tinctures: "Tinkturen",
    concentrates: "Konzentrate",
    topicals: "Topische Anwendungen",
    tryDifferentSearch: "Versuche andere Suchbegriffe oder Filterkriterien",
    results: "Ergebnisse gefunden",
    reviews: "Bewertungen",
    reviewsInSeparateTab: "Bewertungen findest du im Bewertungen-Tab oben",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>("en");

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, t, setLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
